language: go

sudo: required
dist: disco

go:
        - 1.12

before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINARY=golangci-lint sh -s -- -d -b $(go env GOPATH)/bin v1.16.0
        - go get -t -d github.com/subpathdev/cpu-kubeedge-exporter
        - export TRAVIS_BUILD_DIR=$HOME/$GOPATH/src/github.com/subpathdev/cpu-kubeedge-exporter
        - sudo apt-get install build-essential yamllint
        - export PATH=$PATH:$HOME/$GOPATH/bin

install: true

jobs:
        include:
                - stage: "Build Test"
                  script: make
                - stage: "Lint"
                  script: make lint
